begin;

-- Remove only pre-launch events generated by local/browser contract checks.
-- The public site was not launched when these timestamps were recorded.
delete from public.analytics_events
where occurred_at <= timestamptz '2026-08-12 15:10:00+00'
  and (
    (
      event_name = 'service_viewed'
      and page_path in ('/xray.html', '/workforce.html')
    )
    or (
      event_name in ('booking_started', 'booking_abandoned')
      and page_path = '/book.html'
    )
    or (
      anonymous_session_id = 'release-verification-20260812'
      and page_path = '/release-verification'
    )
  );

commit;
